version: "3"

services:
  database:
    image: postgres:latest
    container_name: postgres-styre
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54032:5432